<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Doctrine\\DBAL\\Connection' => 'get1',
  'ThePetPark\\Services\\JWT\\Encoder' => 'get2',
  'ThePetPark\\Services\\JWT\\Decoder' => 'get3',
  'ThePetPark\\Schema\\Container' => 'get4',
  'ThePetPark\\Middleware\\Auth\\Session' => 'get5',
  'subEntry1' => 'get6',
  'ThePetPark\\Middleware\\Auth\\Guard' => 'get7',
  'ThePetPark\\Middleware\\Auth\\Protect' => 'get8',
  'subEntry2' => 'get9',
  'subEntry3' => 'get10',
  'ThePetPark\\Middleware\\Features\\Check' => 'get11',
  'subEntry4' => 'get12',
  'ThePetPark\\Middleware\\Features\\Initialization' => 'get13',
  'ThePetPark\\Middleware\\Features\\Resolver' => 'get14',
  'ThePetPark\\Middleware\\Features\\SparseFieldsets' => 'get15',
  'subEntry5' => 'get16',
  'ThePetPark\\Middleware\\Features\\Filtering' => 'get17',
  'ThePetPark\\Middleware\\Features\\Sorting' => 'get18',
  'ThePetPark\\Middleware\\Features\\ParseIncludes' => 'get19',
  'ThePetPark\\Middleware\\Features\\Pagination\\CursorBased' => 'get20',
  'ThePetPark\\Middleware\\Features\\Pagination\\PageBased' => 'get21',
  'ThePetPark\\Middleware\\Features\\Pagination\\OffsetBased' => 'get22',
  'ThePetPark\\Middleware\\Features\\Pagination\\Links\\CursorBased' => 'get23',
  'ThePetPark\\Middleware\\Features\\Pagination\\Links\\PageBased' => 'get24',
  'ThePetPark\\Middleware\\Features\\Pagination\\Links\\OffsetBased' => 'get25',
  'ThePetPark\\Http\\UploadFile' => 'get26',
  'ThePetPark\\Http\\Session\\Resolve' => 'get27',
  'ThePetPark\\Http\\Session\\Create' => 'get28',
  'subEntry6' => 'get29',
  'subEntry7' => 'get30',
  'ThePetPark\\Http\\Session\\Delete' => 'get31',
  'ThePetPark\\Http\\Passwords\\Set' => 'get32',
  'subEntry8' => 'get33',
  'ThePetPark\\Http\\Passwords\\Update' => 'get34',
  'subEntry9' => 'get35',
  'ThePetPark\\Http\\Actions\\Resolve' => 'get36',
  'ThePetPark\\Http\\Actions\\Add' => 'get37',
  'ThePetPark\\Http\\Actions\\Update' => 'get38',
  'ThePetPark\\Http\\Actions\\Remove' => 'get39',
  'ThePetPark\\Http\\Actions\\Relationships\\Add' => 'get40',
  'ThePetPark\\Http\\Actions\\Relationships\\Remove' => 'get41',
  'ThePetPark\\Http\\Actions\\Relationships\\Update' => 'get42',
  'router' => 'get43',
  'environment' => 'get44',
  'request' => 'get45',
  'response' => 'get46',
  'foundHandler' => 'get47',
  'callableResolver' => 'get48',
  'errorHandler' => 'get49',
  'phpErrorHandler' => 'get50',
  'notFoundHandler' => 'get51',
  'notAllowedHandler' => 'get52',
  'settings' => 'get53',
  'subEntry10' => 'get54',
  'subEntry11' => 'get55',
  'subEntry12' => 'get56',
  'subEntry13' => 'get57',
  'subEntry14' => 'get58',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return \Doctrine\DBAL\DriverManager::getConnection(
            $c->get('settings')['doctrine']['connection']
        );
    }, 'Doctrine\\DBAL\\Connection');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $settings = $c->get('settings')['firebase']['php-jwt'];

        return new \ThePetPark\Services\JWT\Encoder(
            $settings['secret_key'],
            $settings['algorithms'][$settings['selected_algorithm']]
        );
    }, 'ThePetPark\\Services\\JWT\\Encoder');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $settings = $c->get('settings')['firebase']['php-jwt'];

        return new \ThePetPark\Services\JWT\Decoder(
            $settings['secret_key'],
            $settings['algorithms']
        );
    }, 'ThePetPark\\Services\\JWT\\Decoder');
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $definitions = require $c->get('settings')['definitions'];
        $schemas = [];

        foreach ($definitions as $definition) { 
            $schema = \ThePetPark\Schema::fromArray($definition);
            $schemas[$schema->getType()] = $schema;
        }

        return new \ThePetPark\Schema\Container($schemas);
    }, 'ThePetPark\\Schema\\Container');
    }

    protected function get6()
    {
        return $this->delegateContainer->get('ThePetPark\\Services\\JWT\\Decoder');
    }

    protected function get5()
    {
        $object = new ThePetPark\Middleware\Auth\Session($this->get6());
        return $object;
    }

    protected function get7()
    {
        $object = new ThePetPark\Middleware\Auth\Guard();
        return $object;
    }

    protected function get9()
    {
        return $this->delegateContainer->get('Doctrine\\DBAL\\Connection');
    }

    protected function get10()
    {
        return $this->delegateContainer->get('ThePetPark\\Schema\\Container');
    }

    protected function get8()
    {
        $object = new ThePetPark\Middleware\Auth\Protect($this->get9(), $this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('ThePetPark\\Schema\\Container');
    }

    protected function get11()
    {
        $object = new ThePetPark\Middleware\Features\Check($this->get12());
        return $object;
    }

    protected function get13()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Initialization(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class),
            $c->get('settings')['baseUrl']
        );
    }, 'ThePetPark\\Middleware\\Features\\Initialization');
    }

    protected function get14()
    {
        $object = new ThePetPark\Middleware\Features\Resolver();
        return $object;
    }

    protected function get16()
    {
        return $this->delegateContainer->get('ThePetPark\\Schema\\Container');
    }

    protected function get15()
    {
        $object = new ThePetPark\Middleware\Features\SparseFieldsets($this->get16());
        return $object;
    }

    protected function get17()
    {
        $object = new ThePetPark\Middleware\Features\Filtering();
        return $object;
    }

    protected function get18()
    {
        $object = new ThePetPark\Middleware\Features\Sorting();
        return $object;
    }

    protected function get19()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\ParseIncludes($c->get('settings')['baseUrl']);
    }, 'ThePetPark\\Middleware\\Features\\ParseIncludes');
    }

    protected function get20()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\CursorBased($c->get('settings')['defaultPageSize']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\CursorBased');
    }

    protected function get21()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\PageBased($c->get('settings')['defaultPageSize']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\PageBased');
    }

    protected function get22()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\OffsetBased($c->get('settings')['defaultPageSize']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\OffsetBased');
    }

    protected function get23()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\Links\CursorBased($c->get('settings')['baseUrl']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\Links\\CursorBased');
    }

    protected function get24()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\Links\PageBased($c->get('settings')['baseUrl']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\Links\\PageBased');
    }

    protected function get25()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Middleware\Features\Pagination\Links\OffsetBased($c->get('settings')['baseUrl']);
    }, 'ThePetPark\\Middleware\\Features\\Pagination\\Links\\OffsetBased');
    }

    protected function get26()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\UploadFile($c->get('settings')['uploadDirectory']);
    }, 'ThePetPark\\Http\\UploadFile');
    }

    protected function get27()
    {
        $object = new ThePetPark\Http\Session\Resolve();
        return $object;
    }

    protected function get29()
    {
        return $this->delegateContainer->get('Doctrine\\DBAL\\Connection');
    }

    protected function get30()
    {
        return $this->delegateContainer->get('ThePetPark\\Services\\JWT\\Encoder');
    }

    protected function get28()
    {
        $object = new ThePetPark\Http\Session\Create($this->get29(), $this->get30());
        return $object;
    }

    protected function get31()
    {
        $object = new ThePetPark\Http\Session\Delete();
        return $object;
    }

    protected function get33()
    {
        return $this->delegateContainer->get('Doctrine\\DBAL\\Connection');
    }

    protected function get32()
    {
        $object = new ThePetPark\Http\Passwords\Set($this->get33());
        return $object;
    }

    protected function get35()
    {
        return $this->delegateContainer->get('Doctrine\\DBAL\\Connection');
    }

    protected function get34()
    {
        $object = new ThePetPark\Http\Passwords\Update($this->get35());
        return $object;
    }

    protected function get36()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Resolve(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class)
        );
    }, 'ThePetPark\\Http\\Actions\\Resolve');
    }

    protected function get37()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Add(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class),
            $c->get('settings')['baseUrl']
        );
    }, 'ThePetPark\\Http\\Actions\\Add');
    }

    protected function get38()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Update(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class)
        );
    }, 'ThePetPark\\Http\\Actions\\Update');
    }

    protected function get39()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Remove(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class)
        );
    }, 'ThePetPark\\Http\\Actions\\Remove');
    }

    protected function get40()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Relationships\Add(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class),
            $c->get('settings')['baseUrl']
        );
    }, 'ThePetPark\\Http\\Actions\\Relationships\\Add');
    }

    protected function get41()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Relationships\Remove(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class),
            $c->get('settings')['baseUrl'] ?? 'http://localhost'
        );
    }, 'ThePetPark\\Http\\Actions\\Relationships\\Remove');
    }

    protected function get42()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \ThePetPark\Http\Actions\Relationships\Update(
            $c->get(\Doctrine\DBAL\Connection::class),
            $c->get(\ThePetPark\Schema\Container::class)
        );
    }, 'ThePetPark\\Http\\Actions\\Relationships\\Update');
    }

    protected function get43()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $router = new \Slim\Router();

        $router->setContainer($c);
        $router->setCacheFile($c->get('settings')['routerCacheFile']);

        return $router;
    }, 'router');
    }

    protected function get44()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Http\Environment($_SERVER);
    }, 'environment');
    }

    protected function get45()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return \Slim\Http\Request::createFromEnvironment($c->get('environment'));
    }, 'request');
    }

    protected function get46()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $headers = new \Slim\Http\Headers([
            'Content-Type' => 'application/vnd.api+json; charset=UTF-8',
        ]);
        $response = new \Slim\Http\Response(200, $headers);

        return $response->withProtocolVersion($c->get('settings')['httpVersion']);
    }, 'response');
    }

    protected function get47()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Handlers\Strategies\RequestResponse();
    }, 'foundHandler');
    }

    protected function get48()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\CallableResolver($c);
    }, 'callableResolver');
    }

    protected function get49()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Handlers\Error($c->get('settings')['displayErrorDetails']);
    }, 'errorHandler');
    }

    protected function get50()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Handlers\PhpError($c->get('settings')['displayErrorDetails']);
    }, 'phpErrorHandler');
    }

    protected function get51()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Handlers\NotFound();
    }, 'notFoundHandler');
    }

    protected function get52()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \Slim\Handlers\NotAllowed();
    }, 'notAllowedHandler');
    }

    protected function get56()
    {
        return [
            0 => 'HS256',
            1 => 'HS512',
        ];
    }

    protected function get55()
    {
        return [
            'secret_key' => 'C:\\xampp\\htdocs\\cen4010-s21-g01\\server\\api\\v1\\etc/secret.key',
            'algorithms' => $this->get56(),
            'selected_algorithm' => 0,
        ];
    }

    protected function get54()
    {
        return [
            'php-jwt' => $this->get55(),
        ];
    }

    protected function get58()
    {
        return $this->resolveFactory(static function () {
                // Use MySQL config file to initialize the database connection.
                $conf = \parse_ini_file(\dirname('C:\\xampp\\htdocs\\cen4010-s21-g01\\server\\api\\v1\\etc', 4) . '/.my.cnf');

                return [
                    'driver'   => 'pdo_mysql',
                    'host'     => $conf['host'],
                    'port'     => $conf['port'],
                    'dbname'   => $conf['database'],
                    'charset'  => $conf['charset'],
                    'user'     => $conf['user'],
                    'password' => $conf['pass'],
                ];
            }, 'subEntry14');
    }

    protected function get57()
    {
        return [
            'connection' => $this->get58(),
        ];
    }

    protected function get53()
    {
        return [
            'httpVersion' => '1.1',
            'responseChunkSize' => 4096,
            'outputBuffering' => 'append',
            'determineRouteBeforeAppMiddleware' => false,
            'displayErrorDetails' => true,
            'addContentLengthHeader' => true,
            'routerCacheFile' => 'C:\\xampp\\htdocs\\cen4010-s21-g01\\server\\api\\v1/var/cache/routes.php',
            'uploadDirectory' => 'C:\\xampp\\htdocs\\cen4010-s21-g01/public_html/uploads',
            'defaultPageSize' => 12,
            'definitions' => 'C:\\xampp\\htdocs\\cen4010-s21-g01\\server\\api\\v1/var/cache/schemas.php',
            'baseUrl' => 'https://lamp.cse.fau.edu/~cen4010_s21_g01/api-v1.php',
            'firebase' => $this->get54(),
            'doctrine' => $this->get57(),
        ];
    }

}
